#!/usr/bin/env bash

# Script that configures Nginx server with additional settings

# Update package repositories
apt-get -y update

# Install Nginx
apt-get -y install nginx

# Setting up Firewall Rules
ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
if [ -d "/var/www" ]; then
    chown -R "$USER":"$USER" /var/www
    chmod -R 755 /var/www
else
    mkdir -p /var/www
    chown -R "$USER":"$USER" /var/www
    chmod -R 755 /var/www
fi

# Create directories if not present
for dir in /var/www/{html,error}; do
    if ! [ -d "$dir" ]; then
        mkdir -p "$dir"
    fi
done

# Create new index
echo "Hello World!" > /var/www/html/index.html

# Create new error page
echo "Ceci n'est pas une page" > /var/www/html/error_404.html

# Backup default server config file
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.backup

# Set server configuration
server_config=$(cat <<'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By $hostname;
    location / {
        try_files $uri $uri/ =404;
    }
    if ($request_filename ~ redirect_me){
        rewrite ^ https://th3-gr00t.tk/ permanent;
    }
    error_page 404 /error_404.html;
    location = /error_404.html {
        internal;
    }
}
EOF
)

echo "$server_config" | dd status=none of=/etc/nginx/sites-enabled/default

# Restart Nginx service
service nginx restart

