#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy
apt-get -y update
apt-get install -y haproxy -y

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 504881-web-01 52.3.255.107 check
   server 504881-web-02 54.89.119.96 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
