#!/usr/bin/env bash
# Reload Gunicorn in a graceful way

PROCESS_NAME="gunicorn"

PID=$(pgrep -f "^${PROCESS_NAME}" || true)

if [ -z "$PID" ]; then
  echo "No process found for $PROCESS_NAME"
  exit 1
fi

if kill -HUP "$PID"; then
  # Signal sent successfully
  echo "Gunicorn (PID $PID) reloaded gracefully."
else
  # Error sending signal
  echo "Failed to send HUP signal to Gunicorn (PID $PID)."
  exit 1
fi
